name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install --save nodemon sequelize mysql2 jsonwebtoken helmet express dotenv cors body-parser bcryptjs async

    - name: Install Nodemon Globally
      run: npm install -g nodemon

    - name: Build Backend
      run: |
        cd backend
        nodemon

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install -g @vue/cli(babel, eslint, router, vuex) npm install --save axios bcryptjs bootstrap core-js dotenv jquery popper.js vee-validate vue vue-router vuex yup click-outside-vue3

    - name: Build Frontend
      run: |
        cd frontend
        npm run serve
